#!/bin/bash

loader(){
cat <<SHELLEOF
if [ -d ~/.config/shellrc ]; then
    for file in ~/.config/shellrc/*; do
        [ -f "\$file" ] || continue
        source \$file
    done
fi

SHELLEOF
}

omz_section(){
cat <<OMZEOF
export ZSH="\$HOME/.oh-my-zsh"

plugins=(git asdf)

source \$ZSH/oh-my-zsh.sh

OMZEOF
}


if [ -x "$(command -v bash)" ]; then
    loader > "shell/.bashrc"
fi
if [ -x "$(command -v zsh)" ]; then
    loader > "shell/.zshrc"
    omz_section >> "shell/.zshrc"
fi
