#!/usr/bin/env bash

./init

case `hostname` in
    "archwatermelon")
        ./install ghostty nushell nvim scripts tmux
        ;;
    "MacBook-Pro-de-Erik.local")
        ./install aerospace ghostty nushell nvim scripts tmux
        ;;
    *)
        ;;
esac



