#!/usr/bin/env bash

TMUX_CONFIG_PATH="tmux/.config/tmux/tmux.conf"
mkdir -p $(dirname $TMUX_CONFIG_PATH)

BASE_FILE="
set -g default-terminal "tmux-256color"
set -g mouse on
"
echo "$BASE_FILE" > $TMUX_CONFIG_PATH

case `hostname` in
    "archwatermelon")
        echo "set-option -g default-shell \"/usr/bin/nu\"" > $TMUX_CONFIG_PATH
        ;;
    "MacBook-Pro-de-Erik.local")
        echo "set-option -g default-shell \"/opt/homebrew/bin/nu\"" > $TMUX_CONFIG_PATH
        ;;
    *)
        ;;
esac


